"""initial tables

Revision ID: 573977922111
Revises: 
Create Date: 2026-05-13 08:14:56.475311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '573977922111'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('models',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model_name', sa.String(length=128), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('mlflow_run_id', sa.String(length=256), nullable=True),
    sa.Column('total_training_cost_usd', sa.Float(), nullable=True),
    sa.Column('gpu_type', sa.String(length=64), nullable=True),
    sa.Column('gpu_hours', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('training_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model_name', sa.String(length=128), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('comment_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_name', 'comment_id', name='uq_snapshot_model_comment')
    )
    op.create_index('ix_snapshot_model_name', 'training_snapshots', ['model_name'], unique=False)
    op.create_index('ix_snapshot_model_version', 'training_snapshots', ['model_name', 'version'], unique=False)
    op.create_table('model_evaluations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=False),
    sa.Column('f1_score', sa.Float(), nullable=False),
    sa.Column('evaluation_dataset_hash', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('model_evaluations')
    op.drop_index('ix_snapshot_model_version', table_name='training_snapshots')
    op.drop_index('ix_snapshot_model_name', table_name='training_snapshots')
    op.drop_table('training_snapshots')
    op.drop_table('models')
    # ### end Alembic commands ###
