"""New Tables

Revision ID: 6e6bad29f9eb
Revises: 
Create Date: 2026-05-18 10:12:23.552677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e6bad29f9eb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_intent_labels',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('comment_id', sa.UUID(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('intent', sa.String(length=50), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('label_source', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('comment_id', 'model_name', 'version', name='uq_comment_model_version')
    )
    op.create_index('ix_labels_intent', 'model_intent_labels', ['intent'], unique=False)
    op.create_index('ix_labels_model_version', 'model_intent_labels', ['model_name', 'version'], unique=False)
    op.create_index(op.f('ix_model_intent_labels_comment_id'), 'model_intent_labels', ['comment_id'], unique=False)
    op.create_index(op.f('ix_model_intent_labels_intent'), 'model_intent_labels', ['intent'], unique=False)
    op.create_table('models',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model_name', sa.String(length=128), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('mlflow_run_id', sa.String(length=256), nullable=True),
    sa.Column('total_training_cost_usd', sa.Float(), nullable=True),
    sa.Column('gpu_type', sa.String(length=64), nullable=True),
    sa.Column('gpu_hours', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_evaluations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=False),
    sa.Column('f1_score', sa.Float(), nullable=False),
    sa.Column('evaluation_dataset_hash', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('model_evaluations')
    op.drop_table('models')
    op.drop_index(op.f('ix_model_intent_labels_intent'), table_name='model_intent_labels')
    op.drop_index(op.f('ix_model_intent_labels_comment_id'), table_name='model_intent_labels')
    op.drop_index('ix_labels_model_version', table_name='model_intent_labels')
    op.drop_index('ix_labels_intent', table_name='model_intent_labels')
    op.drop_table('model_intent_labels')
    # ### end Alembic commands ###
