"""New intent table

Revision ID: a39fe643718a
Revises: 9730e122c124
Create Date: 2026-05-15 13:13:51.235421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a39fe643718a'
down_revision: Union[str, Sequence[str], None] = '9730e122c124'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_intent_labels',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('comment_id', sa.BigInteger(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('intent', sa.String(length=50), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('label_source', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('comment_id', 'model_name', 'version', name='uq_comment_model_version')
    )
    op.create_index('ix_labels_intent', 'model_intent_labels', ['intent'], unique=False)
    op.create_index('ix_labels_model_version', 'model_intent_labels', ['model_name', 'version'], unique=False)
    op.create_index(op.f('ix_model_intent_labels_comment_id'), 'model_intent_labels', ['comment_id'], unique=False)
    op.create_index(op.f('ix_model_intent_labels_intent'), 'model_intent_labels', ['intent'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_model_intent_labels_intent'), table_name='model_intent_labels')
    op.drop_index(op.f('ix_model_intent_labels_comment_id'), table_name='model_intent_labels')
    op.drop_index('ix_labels_model_version', table_name='model_intent_labels')
    op.drop_index('ix_labels_intent', table_name='model_intent_labels')
    op.drop_table('model_intent_labels')
    # ### end Alembic commands ###
