"""New intent table

Revision ID: f81e7929e729
Revises: 573977922111
Create Date: 2026-05-15 13:09:55.880574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f81e7929e729'
down_revision: Union[str, Sequence[str], None] = '573977922111'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_snapshot_model_name'), table_name='training_snapshots')
    op.drop_index(op.f('ix_snapshot_model_version'), table_name='training_snapshots')
    op.drop_table('training_snapshots')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_snapshots',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('model_name', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('version', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('comment_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('training_snapshots_pkey')),
    sa.UniqueConstraint('model_name', 'comment_id', name=op.f('uq_snapshot_model_comment'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_snapshot_model_version'), 'training_snapshots', ['model_name', 'version'], unique=False)
    op.create_index(op.f('ix_snapshot_model_name'), 'training_snapshots', ['model_name'], unique=False)
    # ### end Alembic commands ###
